Merged revisions 7233-7244 via svnmerge from svn+ssh://svn.code.sf.net/p/scst/svn/trunk
........
  r7233 | bvassche | 2017-09-20 08:09:38 -0700 (Wed, 20 Sep 2017) | 4 lines
  
  ib_srpt: Support systems with more than 255 CPU cores
  
  Signed-off-by: Kirill Malkin <kirillmalkin.km@gmail.com>
........
  r7234 | bvassche | 2017-09-24 18:52:53 -0700 (Sun, 24 Sep 2017) | 2 lines
  
  iscsi-scst/Makefile: Change MOFED path into /usr/src/ofa_kernel/default
........
  r7235 | bvassche | 2017-09-25 16:35:49 -0700 (Mon, 25 Sep 2017) | 1 line
  
  iscsi-scst/Makefile, Ubuntu: Simplify code for version querying
........
  r7236 | bvassche | 2017-10-02 16:56:47 -0700 (Mon, 02 Oct 2017) | 1 line
  
  scripts/specialize-patch: Process ENABLE_NPIV and FC_VPORT_CREATE_DEFINED correctly
........
  r7237 | bvassche | 2017-10-02 17:04:53 -0700 (Mon, 02 Oct 2017) | 2 lines
  
  scripts/generate-kernel-patch: Fix a regression introduced in r7164
........
  r7238 | bvassche | 2017-10-02 17:05:42 -0700 (Mon, 02 Oct 2017) | 1 line
  
  scripts/specialize-patch: Process CONFIG_SCST_STRICT_SERIALIZING correctly
........
  r7239 | bvassche | 2017-10-03 15:49:35 -0700 (Tue, 03 Oct 2017) | 1 line
  
  isert-scst: Make an error message more informative
........
  r7240 | bvassche | 2017-10-03 16:08:29 -0700 (Tue, 03 Oct 2017) | 1 line
  
  scst: Port to kernel v4.13
........
  r7241 | bvassche | 2017-10-03 16:10:03 -0700 (Tue, 03 Oct 2017) | 1 line
  
  nightly build: Update kernel versions
........
  r7242 | bvassche | 2017-10-05 09:57:27 -0700 (Thu, 05 Oct 2017) | 1 line
  
  scst: Port to openSUSE Leap 42.x
........
  r7243 | bvassche | 2017-10-05 16:48:25 -0700 (Thu, 05 Oct 2017) | 1 line
  
  fcst: Port to openSUSE Leap
........
  r7244 | bvassche | 2017-10-05 16:48:51 -0700 (Thu, 05 Oct 2017) | 1 line
  
  qla2x00t: Port to openSUSE Leap
........


git-svn-id: http://svn.code.sf.net/p/scst/svn/branches/3.3.x@7246 d57e44dd-8a1f-0410-8b47-8ef2f437770f

diff --git a/iscsi-scst/Makefile b/iscsi-scst/Makefile
--- a/iscsi-scst/Makefile
+++ b/iscsi-scst/Makefile
@@ -65,23 +65,28 @@ OFED_CFLAGS:=
 OFED_FLAVOR=$(shell if [ -e /usr/bin/ofed_info ]; then /usr/bin/ofed_info 2>/dev/null | head -n1 | sed -n 's/^\(MLNX_OFED\|OFED-internal\).*/MOFED/p;s/^OFED-.*/OFED/p'; else echo in-tree; fi)
 
 ifeq ($(OFED_FLAVOR),MOFED)
-	# Whether MLNX_OFED for ubuntu has been installed
-	MLNX_OFED_IB_UBUNTU_INSTALLED:=$(shell if dpkg -s mlnx-ofed-kernel-dkms >/dev/null 2>/dev/null; then echo true; else echo false; fi)
-
-	# Whether MLNX_OFED for RedHat has been installed
-	MLNX_OFED_IB_RH_INSTALLED:=$(shell if { rpm -q mlnx-ofa_kernel-devel || rpm -q kernel-ib-devel; } >&/dev/null; then echo true; else echo false; fi)
-
-	ifeq ($(MLNX_OFED_IB_UBUNTU_INSTALLED),true)
-	OFED_VERS=$(shell dpkg -s mlnx-ofed-kernel-dkms | awk -F\- '/Version/ {print $$1}' | awk '{print $$2}')
-	OFED_DIR:=/var/lib/dkms/mlnx-ofed-kernel/$(OFED_VERS)/build
-	endif
-
-	ifeq ($(MLNX_OFED_IB_RH_INSTALLED),true)
+	ifeq ($(shell	if dpkg -s mlnx-ofed-kernel-dkms >/dev/null 2>&1; then \
+			  echo true;					       \
+			else						       \
+			  echo false;					       \
+			fi),true)
+	OFED_VERS=$(shell dpkg-query -W --showformat='${Version}\n' mlnx-ofed-kernel-dkms)
+	else
+	ifeq ($(shell	if { rpm -q mlnx-ofa_kernel-devel ||		 \
+			     rpm -q kernel-ib-devel; } >&/dev/null; then \
+			  echo true;					 \
+			else						 \
+			  echo false;					 \
+			fi),true)
 	OFED_VERS=$(shell rpm -q --qf '%{version}\n' mlnx-ofa_kernel-devel \
 			  2>/dev/null)
-	OFED_DIR:=/usr/src/ofa_kernel/default
+	else
+	echo := $(shell echo "Error: MLNX OFED has not been installed" >&2)
+	endif
 	endif
 
+	echo := $(shell echo "OFED_VERS = $(OFED_VERS)" >&2)
+	OFED_DIR:=/usr/src/ofa_kernel/default
 	OFED_CFLAGS:=	-I$(OFED_DIR)/include				\
 			-I$(OFED_DIR)/include/uapi			\
 			-include $(OFED_DIR)/include/linux/compat-2.6.h	\
