scsi_tgt renamed to scst
git-svn-id: http://svn.code.sf.net/p/scst/svn/trunk@169 d57e44dd-8a1f-0410-8b47-8ef2f437770f

diff --git a/scstadmin/init.d/scst b/scstadmin/init.d/scst
--- a/scstadmin/init.d/scst
+++ b/scstadmin/init.d/scst
@@ -40,7 +40,7 @@ case "$1" in
 	done
 
 	rmmod qla2x00tgt || { echo "[qla2x00tgt failed]" ; }
-	rmmod scsi_tgt || { echo "[scsi_tgt failed]" ; }
+	rmmod scst || { echo "[scst failed]" ; }
 	
 	echo "."
 	;;
