Added more error checking.
git-svn-id: http://svn.code.sf.net/p/scst/svn/trunk@1968 d57e44dd-8a1f-0410-8b47-8ef2f437770f

diff --git a/scripts/generate-kernel-with-srp-patches b/scripts/generate-kernel-with-srp-patches
--- a/scripts/generate-kernel-with-srp-patches
+++ b/scripts/generate-kernel-with-srp-patches
@@ -29,6 +29,11 @@ fi
 
 # Actual kernel source generation
 
+if [ -e linux-${kernel_version} -o -e linux-$1 ]; then
+  echo "Error: directoy not clean."
+  exit 1
+fi
+
 echo "Extracting kernel sources ..."
 tar xaf $TARBALLDIR/linux-${kernel_version}.tar.bz2 || exit $?
 if [ "${patch_level}" != "" ]; then
