scripts: Merge r7826:8001 from trunk
git-svn-id: http://svn.code.sf.net/p/scst/svn/branches/3.3.x@8006 d57e44dd-8a1f-0410-8b47-8ef2f437770f

diff --git a/scripts/run-regression-tests b/scripts/run-regression-tests
--- a/scripts/run-regression-tests
+++ b/scripts/run-regression-tests
@@ -292,6 +292,7 @@ CONFIG_MMIOTRACE				\
 CONFIG_NET_DROP_MONITOR				\
 CONFIG_NOP_TRACER				\
 CONFIG_SCHED_TRACER				\
+CONFIG_SECURITY_SELINUX				\
 CONFIG_STACK_TRACER				\
 CONFIG_STACK_VALIDATION				\
 CONFIG_TRACEPOINTS				\
@@ -603,7 +604,6 @@ if [ "${run_local_compilation}" = "true" ]; then
   compile_scst_no_dlm    || exit $?
   compile_scst_patched 2release || exit $?
   compile_scst_patched 2perf    || exit $?
-  compile_scst_patched enable_proc  || exit $?
   if type rpmbuild >/dev/null 2>&1; then
       make_rpm || exit $?
   fi
@@ -648,7 +648,10 @@ do
   patchdir="patchdir-${kv}"
   k="${kv}"
 
-  download_kernel "$k" || continue
+  if ! download_kernel "$k"; then
+    echo "Downloading kernel version $k failed"
+    continue
+  fi
   generate_kernel_patch "$k" "${generate_kernel_patch_options}" || continue
   (
       cd "${outputdir}" &&
