Merged revisions 6703-6718,6720-6721 via svnmerge from svn+ssh://vlnb@svn.code.sf.net/p/scst/svn/trunk
........
  r6703 | bvassche | 2015-11-19 08:53:18 -0800 (Thu, 19 Nov 2015) | 5 lines
  
  scst_sysfs: Introduce scst_parse_add_repl_param()
  
  This makes the __scst_process_luns_mgmt_store() source code slightly
  easier to read.
........
  r6704 | bvassche | 2015-11-19 09:30:24 -0800 (Thu, 19 Nov 2015) | 1 line
  
  scripts/run-regression-tests: Also test no-DLM build
........
  r6705 | bvassche | 2015-11-19 09:31:02 -0800 (Thu, 19 Nov 2015) | 1 line
  
  scst: Fix procfs build
........
  r6706 | bvassche | 2015-11-19 09:48:18 -0800 (Thu, 19 Nov 2015) | 1 line
  
  scst: More procfs build fixes. See also r6694.
........
  r6707 | bvassche | 2015-11-20 13:47:57 -0800 (Fri, 20 Nov 2015) | 5 lines
  
  scst_local: Linux kernel v4.4 build fix
  
  Signed-off-by: Sebastian Herbszt <herbszt@gmx.de>
  [ bvanassche: Merged the two #if-statements into a single #if-statement ]
........
  r6708 | bvassche | 2015-11-20 15:23:48 -0800 (Fri, 20 Nov 2015) | 2 lines
  
  /etc/init.d/scst: Suppress rmmod error messages
........
  r6709 | bvassche | 2015-11-20 16:19:04 -0800 (Fri, 20 Nov 2015) | 5 lines
  
  scstadmin: Improve copy manager support
  
  Add support for saving and restoring copy manager attributes.
........
  r6710 | bvassche | 2015-11-22 11:49:18 -0800 (Sun, 22 Nov 2015) | 4 lines
  
  qla2x00t: Fix a few typos
  
  Signed-off-by: Sebastian Herbszt <herbszt@gmx.de>
........
  r6711 | bvassche | 2015-11-22 12:03:29 -0800 (Sun, 22 Nov 2015) | 7 lines
  
  mpt: Include header file mptbase.h without path
  
  Allow include path modification with LSI_INC_DIR.
  
  Signed-off-by: Sebastian Herbszt <herbszt@gmx.de>
........
  r6712 | bvassche | 2015-11-23 15:04:57 -0800 (Mon, 23 Nov 2015) | 4 lines
  
  scstadmin: Improve copy manager support further
  
  Also restore pass-through LUNs
........
  r6713 | bvassche | 2015-11-23 15:05:24 -0800 (Mon, 23 Nov 2015) | 2 lines
  
  scstadmin: Make regression test 6 pass
........
  r6714 | bvassche | 2015-11-25 09:28:02 -0800 (Wed, 25 Nov 2015) | 6 lines
  
  usr/fileio: Build fix for Ubuntu 15.10
  
  Ubuntu 15.10 includes Linux kernel 4.2 but does not define
  SERVICE_ACTION_IN_16 in the <scsi/scsi.h> glibc header. Hence
  provide a definition in scst_const.h.
........
  r6715 | bvassche | 2015-11-27 20:39:57 -0800 (Fri, 27 Nov 2015) | 1 line
  
  scst-const.h: Follow-up for r6714
........
  r6716 | bvassche | 2015-12-02 08:57:45 -0800 (Wed, 02 Dec 2015) | 1 line
  
  scst: Rename the PR-sync document to avoid filenames with spaces in the SCST tree
........
  r6717 | bvassche | 2015-12-02 14:59:33 -0800 (Wed, 02 Dec 2015) | 1 line
  
  scstadmin: Ensure that -no_lip takes effect for all SCST configuration commands
........
  r6718 | bvassche | 2015-12-03 16:31:40 -0800 (Thu, 03 Dec 2015) | 1 line
  
  nightly build: Update kernel versions
........
  r6720 | vlnb | 2015-12-07 19:44:51 -0800 (Mon, 07 Dec 2015) | 3 lines
  
  docs: fix (extra)clean brocken by r6716
........
  r6721 | vlnb | 2015-12-07 19:51:01 -0800 (Mon, 07 Dec 2015) | 3 lines
  
  Cleanup
........


git-svn-id: http://svn.code.sf.net/p/scst/svn/branches/3.1.x@6722 d57e44dd-8a1f-0410-8b47-8ef2f437770f

diff --git a/scripts/run-regression-tests b/scripts/run-regression-tests
--- a/scripts/run-regression-tests
+++ b/scripts/run-regression-tests
@@ -141,6 +141,26 @@ function compile_scst_unpatched {
   )
 }
 
+# Compile the unpatched SCST source code without DLM.
+function compile_scst_no_dlm {
+  local scst="$PWD"
+  local outputfile="${outputdir}/compilation-output-no-dlm.txt"
+  local workingdirectory="${outputdir}/scst-no-dlm"
+
+  echo "Testing whether the SCST tree compiles fine without DLM support ..."
+  (
+    if mkdir -p "${workingdirectory}"  \
+       && cd "${workingdirectory}"     \
+       && duplicate_scst_source_tree "${scst}"  \
+       && CONFIG_SCST_NO_DLM=y compile_scst &> "${outputfile}"
+    then
+      echo "OK"
+    else
+      echo "FAILED"
+    fi
+  )
+}
+
 # Test out-of-tree compilation agains the kernel header files in
 # /lib/modules/$(uname -r)/build.
 function compile_scst_patched {
@@ -558,6 +578,7 @@ fi
 test_scst_tree_patches || exit $?
 if [ "${run_local_compilation}" = "true" ]; then
   compile_scst_unpatched || exit $?
+  compile_scst_no_dlm    || exit $?
   compile_scst_patched 2release || exit $?
   compile_scst_patched 2perf    || exit $?
   compile_scst_patched enable_proc  || exit $?
