scripts: Merge r5177 from trunk
git-svn-id: http://svn.code.sf.net/p/scst/svn/branches/2.2.x@5372 d57e44dd-8a1f-0410-8b47-8ef2f437770f

diff --git a/scripts/run-regression-tests b/scripts/run-regression-tests
--- a/scripts/run-regression-tests
+++ b/scripts/run-regression-tests
@@ -96,6 +96,17 @@ function duplicate_scst_source_tree {
   fi
 }
 
+function make_rpm {
+    local outputfile="${outputdir}/make-rpm-output.txt"
+
+    echo "Testing whether 'make rpm' works fine ..."
+    if make rpm > "${outputfile}" 2>&1; then
+	echo "OK"
+    else
+	echo "FAILED"
+    fi
+}
+
 function compile_scst {
   (
     export KCFLAGS=-DCONFIG_SCST_MEASURE_LATENCY
@@ -555,6 +566,9 @@ if [ "${run_local_compilation}" = "true" ]; then
   compile_scst_patched debug2release || exit $?
   compile_scst_patched debug2perf    || exit $?
   compile_scst_patched enable_proc  || exit $?
+  if type rpmbuild >/dev/null 2>&1; then
+      make_rpm || exit $?
+  fi
 fi
 
 first_iteration="true"
